In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('data/SMSSpamCollection.csv', sep = '\t', header=None)
df = df.sample(frac=1, axis=1).sample(frac=1).reset_index(drop=True)

split_frac = 0.8
split_idx = round(split_frac * df.shape[0])

df_train = df.iloc[:split_idx, :]
df_test = df.iloc[split_idx:, :]


In [3]:
# first, we need to create the features from text. we are interested in createing 
# a dictionary of words. Requires splitting on space and removing punctuation.

In [4]:
import re
from collections import Counter

doc_counter = {}
doc_counter['ham'] = Counter()
doc_counter['spam'] = Counter()
for label in ['ham', 'spam']:
    for i in range(df_train.shape[0]):
        curr_label = df_train.loc[i, 0]
        if curr_label == label:
            example = df_train.loc[i, 1]
            words = example.split(' ')
            words=[re.sub(r'[^\w\s]','', word) for word in words]
            doc_counter[label] = doc_counter[label] + Counter(list(set(words)))


In [5]:
y_train = df_train.iloc[:,0]
n = {}
n['ham'] = sum(y_train == 'ham') # number of documents that are ham
n['spam'] = sum(y_train == 'spam') # number of documents taht are spam
n_docs= n['ham']  +n['spam'] 
prior = {}
prior['ham'] = n['ham'] /n_docs
prior['spam'] = n['spam']/n_docs
num_words = len(doc_counter['ham'] + doc_counter['spam'])

prob_ham_test = np.zeros(shape = df_test.shape[0])
for i in range(df_test.shape[0]):
    example = df_test.iloc[i, 1]
    words = example.split(' ')
    words = [re.sub(r'[^\w\s]','', word) for word in words]
    words = list(set(words))
    
    prob = {}
    for label in ['ham', 'spam']:
        likelihood = 1
        for word in words:
            prob_word_given_label = (doc_counter[label][word]+1)/(n[label] + num_words)
            likelihood = likelihood * prob_word_given_label
        prob[label] = likelihood * prior[label]
    
    prob_ham_scaled = prob['ham']/(prob['ham'] + prob['spam'])
    prob_ham_test[i] = prob_ham_scaled
prob_ham_test

array([0.99778132, 0.99999998, 0.99999968, ..., 0.99997929, 0.99999108,
       0.99999999])

In [6]:
y_test = df_test.iloc[:,0]
is_ham_test =  np.array(1*(y_test == 'ham'))
is_ham_test

array([1, 1, 1, ..., 1, 1, 1])

In [7]:
threshold = 0.5
TP = sum(is_ham_test * (prob_ham_test > threshold))
FP = sum(np.logical_not(is_ham_test) * (prob_ham_test > threshold))
TN = sum(np.logical_not(is_ham_test) * (prob_ham_test < threshold))
FN = sum(is_ham_test * (prob_ham_test < threshold))

In [8]:
# Confusion matrix

# rows are labels
# cols are predictions

C = np.array([[TN, FP],
              [FN, TP]])
C

array([[107,  39],
       [  3, 965]])

In [9]:
precision = TP / (TP + FP)
precision 

0.9611553784860558

In [10]:
recall = TP / (TP + FN)
recall 

0.996900826446281

# Scikit-Learn version